---
- name: setup fda stack
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ aws.region }}"
    disable_rollback: false
    template: "roles/stack/files/stack_template.json"
    template_parameters: "{{ stackParameters }}"
  register: "fdaStack"

- name: read stack output
  debug: msg="{{ fdaStack.stack_outputs }}"

# Assign newly created IAM roles to exiting Identity Pool

- name: assign Cognito Identity Pool roles
  command: >
    aws cognito-identity
    set-identity-pool-roles
    --identity-pool-id "{{ ExistingIdentityPoolId.stdout }}"
    --roles "unauthenticated={{ fdaStack.stack_outputs.UnAuthRole }},
             authenticated={{ fdaStack.stack_outputs.AuthRole }}"
