---
- hosts: "nowhere"
  connection: "local"
  gather_facts: False
  roles:
    - { role: "engine", tags: ["engine"] }
    - { role: "cognito", tags: ["cognito"] }
    - { role: "stack", tags: ["stack"] }
    - { role: "camera", tags: ["camera"] }
    - { role: "facewall", tags: ["facewall"] }
