---
app_name: "in-development"

stack_name: "fda-{{ app_name }}-stack"

aws:
  region: "eu-west-1" # must support all resources

identityPoolName: "fda {{ app_name | regex_replace('-', ' ') }}"

EngineBucket: "fda-{{ app_name }}-engine"
MainBucket: "fda-{{ app_name }}-main"

camera_name: "{{ app_name }}"

db_snapshot: "snapshot"
db_resources_counter: "resources-counter"

stackParameters:
  MainBucketName: "{{ MainBucket }}"
  EngineBucketName: "{{ EngineBucket }}"
  EngineS3PolicyName: "fda-{{ app_name }}-engine-s3-policy"
  CameraS3PolicyName: "fda-{{ app_name }}-camera-s3-policy"
  DBCameraPolicyName: "fda-{{ app_name }}-db-camera-policy"
  DBEnginePolicyName: "fda-{{ app_name }}-db-engine-policy"
  SyncAccessPolicyName: "fda-{{ app_name }}-sync-access-policy"
  EngineLogPolicyName: "fda-{{ app_name }}-engine-log-policy"
  IdentityPoolId: "{{ ExistingIdentityPoolId.stdout }}"
  DBResourcesCounter: "{{ db_resources_counter }}"
  DBSnapshot: "{{ db_snapshot }}"
  SnapshotDBTableName: "fda-{{ app_name }}-{{ db_snapshot }}"
  ResourcesCounterDBTableName: "fda-{{ app_name }}-{{ db_resources_counter }}"
  SnapshotDBIndexName: "cameraid-unixtimestamp-index"
  EngineLambdaFunctionName: "fda-{{ app_name }}-engine"
