---
app_name: "in-development"

stack_name: "fda-{{ app_name }}-stack"

aws:
  region: "eu-west-1" # must support all resources

identityPoolName: "fda {{ app_name | regex_replace('-', ' ') }}"

EngineBucket: "fda-{{ app_name }}-engine"

stackParameters:
  MainBucketName: "fda-{{ app_name }}-main"
  EngineBucketName: "{{ EngineBucket }}"
  EngineS3PolicyName: "fda-{{ app_name }}-engine-s3-policy"
  CameraS3PolicyName: "fda-{{ app_name }}-camera-s3-policy"
  DBCameraPolicyName: "fda-{{ app_name }}-db-camera-policy"
  DBEnginePolicyName: "fda-{{ app_name }}-db-engine-policy"
  SyncAccessPolicyName: "fda-{{ app_name }}-sync-access-policy"
  EngineLogPolicyName: "fda-{{ app_name }}-engine-log-policy"
  IdentityPoolId: "{{ ExistingIdentityPoolId.stdout }}"
  SnapshotDBTableName: "fda-{{ app_name }}-snapshot"
  ResourcesCounterDBTableName: "fda-{{ app_name }}-resources-counter"
  SnapshotDBIndexName: "cameraid-unixtimestamp-index"
  EngineLambdaFunctionName: "fda-{{ app_name }}-engine"
