---
# Create or Update Cloudformation Stack

- name: stackParameters
  debug: msg={{ stackParameters }}

- name: setup fda stack
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ aws.region }}"
    disable_rollback: false
    template: "roles/app_stack/files/stack_template.json"
    template_parameters: "{{ stackParameters }}"
  register: "fdaStack"

- name: read stack output
  debug: msg="{{ fdaStack.stack_outputs }}"

# Assign newly created IAM roles to exiting Identity Pool

- name: assign Cognito Identity Pool roles
  command: >
    aws cognito-identity
    set-identity-pool-roles
    --identity-pool-id "{{ ExistingIdentityPoolId.stdout }}"
    --roles "unauthenticated={{ fdaStack.stack_outputs.UnAuthRole }},
             authenticated={{ fdaStack.stack_outputs.AuthRole }}"

# Camera App

- name: empty the camera directory
  file: path=camera state=absent

- name: create camera directory
  file: path=camera state=directory

- name: copy camera source
  git:
    repo=https://github.com/ricardosllm/fda-camera.git
    dest=camera
    version=master

- name: build camera config
  template:
    src=camera.config.js
    dest=camera/js/app/config.js

- name: upload camera app
  command: >
    aws s3 sync ./camera s3://{{ MainBucket }}/camera
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*.svg"

- name: upload camera assets
  command: >
    aws s3 sync ./camera s3://{{ MainBucket }}/camera
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*" --include "*.svg" --content-type "image/svg+xml"

- name: Build Main bucket cors config
  template:
    src=cors.json
    dest=camera/cors.json

- name: Upload Main bucket cors config
  command: >
    aws s3api put-bucket-cors --bucket {{ MainBucket }}
    --cors-configuration file://camera/cors.json

# Facewall App

- name: empty the facewall directory
  file: path=facewall state=absent

- name: create facewall directory
  file: path=facewall state=directory

- name: copy facewall source
  git:
    repo=https://github.com/ricardosllm/fda-facewall.git
    dest=facewall
    version=master

- name: build facewall config
  template:
    src=facewall.config.js
    dest=facewall/js/app/config.js

- name: upload facewall app
  command: >
    aws s3 sync ./facewall s3://{{ MainBucket }}/facewall
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*.svg"

- name: upload facewall assets
  command: >
    aws s3 sync ./facewall s3://{{ MainBucket }}/facewall
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*" --include "*.svg" --content-type "image/svg+xml"

# TODO: Fix error with facewall db access
# TODO: Update camera and facewall page title
