---
- name: empty the camera directory
  file: path=camera state=absent

- name: create camera directory
  file: path=camera state=directory

- name: copy camera source
  git:
    repo=https://github.com/ricardosllm/fda-camera.git
    dest=camera
    version=master

- name: build camera config
  template:
    src=camera.config.js
    dest=camera/js/app/config.js

- name: upload camera app
  command: >
    aws s3 sync ./camera s3://{{ MainBucket }}/camera
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*.svg"

- name: upload camera assets
  command: >
    aws s3 sync ./camera s3://{{ MainBucket }}/camera
    --acl "public-read" --exclude "*._*" --exclude ".DS_Store"
    --exclude "*" --include "*.svg" --content-type "image/svg+xml"

- name: Build Main bucket cors config
  template:
    src=cors.json
    dest=camera/cors.json

- name: Upload Main bucket cors config
  command: >
    aws s3api put-bucket-cors --bucket {{ MainBucket }}
    --cors-configuration file://camera/cors.json
