---
- name: List Cognito Identity Pools
  command: >
    aws cognito-identity
    list-identity-pools
    --max-results 5
  register: identityPoolList

- name: register existing identityPoolName
  shell: 'echo {{ (identityPoolList.stdout | from_json)["IdentityPools"][0]["IdentityPoolName"] }}'
  register: ExistingIdentityPoolName

- name: create Cognito Identity Pool
  command: >
    aws cognito-identity
    create-identity-pool
    --identity-pool-name "{{ identityPoolName }}"
    --allow-unauthenticated-identities
  register: NewIdentityPoolId
  when: ExistingIdentityPoolName.stdout != identityPoolName

- name: register new identityPoolId
  shell: 'echo {{ NewIdentityPoolId }}' # FIXME when creating new pool
  register: ExistingIdentityPoolId
  when: ExistingIdentityPoolName.stdout != identityPoolName

- name: register existing identityPoolId
  shell: 'echo {{ (identityPoolList.stdout | from_json)["IdentityPools"][0]["IdentityPoolId"] }}'
  register: ExistingIdentityPoolId
  when: NewIdentityPoolId["skipped"] == true

- name: ExistingIdentityPoolId.stdout
  debug: msg={{ ExistingIdentityPoolId.stdout }}
