---
- name: Create bucket
  s3:
    bucket: "{{ EngineBucket }}"
    permission: "public-read"
    region: "{{ aws.region }}"
    mode: "create"

- name: empty directory
  file: path=engine state=absent

- name: create directory
  file: path=engine state=directory

- name: copy source
  git:
    repo=https://github.com/ricardosllm/fda-engine.git
    dest=engine
    version=master

- name: build config
  template:
    src=engine.config.js
    dest=engine/index/config.js

- name: Remove example
  file: path=engine/index/config.js.example state=absent

- name: Compile node source
  shell: "zip -r index.zip ./index/"
  args:
    chdir: "engine"

- name: Upload node source
  shell: 'aws s3 cp index.zip s3://{{ EngineBucket }}'
  args:
    chdir: "engine"
